// ─── Demo mode – in-memory data ─────────────────────────────────────────────
// Realistic Polish job listings and user data used when DEMO_MODE=true

import type { CVProfile, JobListing, MatchScore, Application, Alert, UserProfile } from '../types/index.js';

export const DEMO_USER_ID = 'demo-user-00000000-0000-0000-0000-000000000001';

export const DEMO_PROFILE: UserProfile = {
  id: DEMO_USER_ID,
  email: 'demo@worksmart.pl',
  plan: 'pro',
  created_at: '2026-01-01T10:00:00Z',
};

export const DEMO_CV: CVProfile = {
  id: 'demo-cv-00000000-0000-0000-0000-000000000001',
  user_id: DEMO_USER_ID,
  raw_text: 'Jan Kowalski – Frontend Developer z 3-letnim doświadczeniem...',
  skills: ['React', 'TypeScript', 'Node.js', 'Git', 'Tailwind CSS', 'REST API', 'SQL', 'Figma', 'Agile / Scrum', 'Jest'],
  experience: [
    { company: 'Allegro', role: 'Junior Frontend Developer', start: '2023-03', end: '2025-06', description: 'Budowanie komponentów React, optymalizacja wydajności, code review.' },
    { company: 'StartupXYZ', role: 'Stażysta webdev', start: '2022-07', end: '2023-02', description: 'HTML/CSS, podstawy JavaScript, WordPress.' },
  ],
  education: [
    { institution: 'Politechnika Warszawska', degree: 'Inżynier', field: 'Informatyka', graduation: '2022' },
  ],
  ats_score: 72,
  suggestions: [
    { issue: 'Brak słów kluczowych związanych z testowaniem', fix: 'Dodaj "Jest", "React Testing Library" do sekcji Umiejętności', impact: 'high' },
    { issue: 'Sekcja Podsumowanie jest zbyt krótka', fix: 'Rozwiń do 3-4 zdań opisujących specjalizację i główne osiągnięcia', impact: 'medium' },
    { issue: 'Brak linku do portfolio lub GitHuba', fix: 'Dodaj URL do profilu GitHub lub portfolio w nagłówku CV', impact: 'medium' },
  ],
  created_at: '2026-01-15T12:00:00Z',
  updated_at: '2026-03-10T09:30:00Z',
};

export const DEMO_JOBS: JobListing[] = [
  {
    id: 'job-00000001',
    external_id: 'jj_senior-react-dev-warsaw',
    source: 'justjoin',
    title: 'Senior React Developer',
    company: 'Allegro Pay',
    location: 'Warszawa',
    remote_type: 'hybrid',
    salary_min: 18000,
    salary_max: 26000,
    currency: 'PLN',
    description: 'Szukamy doświadczonego React Developera do zespołu budującego produkty płatnicze. Pracujesz z mikrofrontendami, design systemem i nowoczesnymi narzędziami.',
    requirements: ['React', 'TypeScript', 'Redux', 'GraphQL', 'Jest', 'Webpack', '5+ lat doświadczenia'],
    url: 'https://justjoin.it/offers/allegro-pay-senior-react-developer',
    is_active: true,
    scraped_at: '2026-04-13T07:00:00Z',
  },
  {
    id: 'job-00000002',
    external_id: 'jj_mid-frontend-dev-remote',
    source: 'justjoin',
    title: 'Mid Frontend Developer',
    company: 'Boldare',
    location: 'Zdalnie',
    remote_type: 'remote',
    salary_min: 12000,
    salary_max: 18000,
    currency: 'PLN',
    description: 'Dołącz do produktowego software house\'u. Pracujesz bezpośrednio z klientami z USA i UK, budujesz aplikacje SaaS od zera.',
    requirements: ['React', 'TypeScript', 'REST API', 'Git', 'Tailwind CSS', 'Figma', '2+ lat doświadczenia'],
    url: 'https://justjoin.it/offers/boldare-mid-frontend-developer',
    is_active: true,
    scraped_at: '2026-04-13T07:00:00Z',
  },
  {
    id: 'job-00000003',
    external_id: 'nfj_fullstack-ts-krakow',
    source: 'nofluffjobs',
    title: 'Fullstack Developer (TypeScript)',
    company: 'Brainly',
    location: 'Kraków',
    remote_type: 'hybrid',
    salary_min: 14000,
    salary_max: 20000,
    currency: 'PLN',
    description: 'Rozwijamy platformę edukacyjną używaną przez 350 milionów uczniów na świecie. Stack: React, Node.js, PostgreSQL, Kubernetes.',
    requirements: ['TypeScript', 'React', 'Node.js', 'SQL', 'Docker', 'Git', 'Agile'],
    url: 'https://nofluffjobs.com/pl/job/brainly-fullstack-developer',
    is_active: true,
    scraped_at: '2026-04-13T07:00:00Z',
  },
  {
    id: 'job-00000004',
    external_id: 'rj_react-native-dev',
    source: 'rocketjobs',
    title: 'React Native Developer',
    company: 'ING Hubs Poland',
    location: 'Warszawa',
    remote_type: 'hybrid',
    salary_min: 16000,
    salary_max: 22000,
    currency: 'PLN',
    description: 'Rozwijaj mobilną aplikację bankową używaną przez miliony klientów. Praca w stabilnym środowisku fintech z dużymi możliwościami rozwoju.',
    requirements: ['React Native', 'TypeScript', 'Redux', 'REST API', 'iOS/Android basics', 'Git'],
    url: 'https://rocketjobs.pl/ing-hubs-react-native-developer',
    is_active: true,
    scraped_at: '2026-04-12T19:00:00Z',
  },
  {
    id: 'job-00000005',
    external_id: 'pracuj_fe-dev-poznan',
    source: 'pracuj',
    title: 'Frontend Developer',
    company: 'Ramp Network',
    location: 'Poznań',
    remote_type: 'remote',
    salary_min: 10000,
    salary_max: 16000,
    currency: 'PLN',
    description: 'Budujemy infrastrukturę crypto payments dla startupów z całego świata. Zwinny zespół, duża autonomia, ciekawa technologia.',
    requirements: ['React', 'JavaScript', 'TypeScript', 'CSS', 'REST API', 'Git', 'Testy jednostkowe'],
    url: 'https://pracuj.pl/praca/ramp-network-frontend-developer',
    is_active: true,
    scraped_at: '2026-04-12T19:00:00Z',
  },
  {
    id: 'job-00000006',
    external_id: 'olx_junior-react-wroclaw',
    source: 'olx',
    title: 'Junior React Developer',
    company: 'Netguru',
    location: 'Wrocław',
    remote_type: 'hybrid',
    salary_min: 7000,
    salary_max: 11000,
    currency: 'PLN',
    description: 'Szukamy juniora z pasją do frontendu. Mentoring, wewnętrzne szkolenia, praca przy projektach dla startupów z Doliny Krzemowej.',
    requirements: ['React', 'JavaScript', 'HTML/CSS', 'Git', 'Chęć do nauki'],
    url: 'https://www.olx.pl/oferta/netguru-junior-react-developer',
    is_active: true,
    scraped_at: '2026-04-12T19:00:00Z',
  },
  {
    id: 'job-00000007',
    external_id: 'jj_node-backend-dev',
    source: 'justjoin',
    title: 'Node.js Backend Developer',
    company: 'DocPlanner',
    location: 'Warszawa',
    remote_type: 'remote',
    salary_min: 15000,
    salary_max: 21000,
    currency: 'PLN',
    description: 'Platforma łącząca lekarzy z pacjentami w 13 krajach. Rozwijasz mikroserwisy Node.js obsługujące miliony wizyt miesięcznie.',
    requirements: ['Node.js', 'TypeScript', 'PostgreSQL', 'Redis', 'Docker', 'REST API', 'Mikroserwisy'],
    url: 'https://justjoin.it/offers/docplanner-nodejs-backend-developer',
    is_active: true,
    scraped_at: '2026-04-13T07:00:00Z',
  },
  {
    id: 'job-00000008',
    external_id: 'nfj_ux-ui-designer-remote',
    source: 'nofluffjobs',
    title: 'UX/UI Designer',
    company: 'Tidio',
    location: 'Zdalnie',
    remote_type: 'remote',
    salary_min: 9000,
    salary_max: 14000,
    currency: 'PLN',
    description: 'Projektuj interfejsy dla narzędzia do obsługi klienta używanego przez 300 tys. firm. Pracujesz w Figma, prowadzisz badania UX.',
    requirements: ['Figma', 'UX research', 'Prototypowanie', 'Design systems', 'User testing'],
    url: 'https://nofluffjobs.com/pl/job/tidio-ux-ui-designer',
    is_active: true,
    scraped_at: '2026-04-13T07:00:00Z',
  },
];

export const DEMO_MATCHES: MatchScore[] = [
  {
    id: 'match-00000001',
    user_id: DEMO_USER_ID,
    job_id: 'job-00000002',
    score: 89,
    missing_skills: ['Figma'],
    matching_skills: ['React', 'TypeScript', 'REST API', 'Git', 'Tailwind CSS'],
    recommendation: 'Bardzo dobre dopasowanie! Masz 5 z 7 wymaganych umiejętności. Dodaj Figma do CV jeśli choć trochę z niej korzystałeś.',
    computed_at: '2026-04-13T08:00:00Z',
    job: DEMO_JOBS.find(j => j.id === 'job-00000002'),
  },
  {
    id: 'match-00000002',
    user_id: DEMO_USER_ID,
    job_id: 'job-00000005',
    score: 82,
    missing_skills: ['Testy jednostkowe'],
    matching_skills: ['React', 'JavaScript', 'TypeScript', 'CSS', 'REST API', 'Git'],
    recommendation: 'Dobre dopasowanie. Dodaj informacje o testach (Jest) do CV – to jedyna luka.',
    computed_at: '2026-04-13T08:00:00Z',
    job: DEMO_JOBS.find(j => j.id === 'job-00000005'),
  },
  {
    id: 'match-00000003',
    user_id: DEMO_USER_ID,
    job_id: 'job-00000003',
    score: 76,
    missing_skills: ['Docker', 'Node.js (zaawansowany)'],
    matching_skills: ['TypeScript', 'React', 'SQL', 'Git', 'Agile'],
    recommendation: 'Solidne dopasowanie na poziomie frontendu. Warto podkreślić znajomość SQL i doświadczenie z Agile.',
    computed_at: '2026-04-13T08:00:00Z',
    job: DEMO_JOBS.find(j => j.id === 'job-00000003'),
  },
  {
    id: 'match-00000004',
    user_id: DEMO_USER_ID,
    job_id: 'job-00000006',
    score: 91,
    missing_skills: [],
    matching_skills: ['React', 'JavaScript', 'HTML/CSS', 'Git'],
    recommendation: 'Idealne dopasowanie! Twoje doświadczenie zdecydowanie przewyższa wymagania tej oferty.',
    computed_at: '2026-04-13T08:00:00Z',
    job: DEMO_JOBS.find(j => j.id === 'job-00000006'),
  },
  {
    id: 'match-00000005',
    user_id: DEMO_USER_ID,
    job_id: 'job-00000007',
    score: 61,
    missing_skills: ['PostgreSQL', 'Redis', 'Docker', 'Mikroserwisy'],
    matching_skills: ['Node.js', 'TypeScript', 'REST API'],
    recommendation: 'Częściowe dopasowanie – mocna strona to TypeScript i Node.js. Brakuje znajomości backendowego stacku (DB, Docker).',
    computed_at: '2026-04-13T08:00:00Z',
    job: DEMO_JOBS.find(j => j.id === 'job-00000007'),
  },
  {
    id: 'match-00000006',
    user_id: DEMO_USER_ID,
    job_id: 'job-00000001',
    score: 54,
    missing_skills: ['Redux', 'GraphQL', 'Webpack', '5+ lat doświadczenia'],
    matching_skills: ['React', 'TypeScript', 'Jest'],
    recommendation: 'Za wcześnie na tę ofertę – wymaga 5+ lat i zaawansowanych narzędzi. Wróć za 2-3 lata lub uzupełnij stack.',
    computed_at: '2026-04-13T08:00:00Z',
    job: DEMO_JOBS.find(j => j.id === 'job-00000001'),
  },
];

export const DEMO_APPLICATIONS: Application[] = [
  {
    id: 'app-00000001',
    user_id: DEMO_USER_ID,
    job_id: 'job-00000002',
    status: 'interview',
    applied_at: '2026-04-05T10:00:00Z',
    notes: 'Rozmowa techniczna 16.04 o 14:00',
    job: DEMO_JOBS.find(j => j.id === 'job-00000002'),
  },
  {
    id: 'app-00000002',
    user_id: DEMO_USER_ID,
    job_id: 'job-00000005',
    status: 'sent',
    applied_at: '2026-04-10T15:30:00Z',
    notes: '',
    job: DEMO_JOBS.find(j => j.id === 'job-00000005'),
  },
  {
    id: 'app-00000003',
    user_id: DEMO_USER_ID,
    job_id: 'job-00000003',
    status: 'rejected',
    applied_at: '2026-03-28T09:00:00Z',
    notes: 'Brak doświadczenia z Docker',
    job: DEMO_JOBS.find(j => j.id === 'job-00000003'),
  },
];

export const DEMO_ALERTS: Alert[] = [
  {
    id: 'alert-00000001',
    user_id: DEMO_USER_ID,
    min_score: 80,
    keywords: ['React', 'TypeScript'],
    locations: ['Warszawa', 'Zdalnie'],
    is_active: true,
    last_sent_at: '2026-04-12T19:05:00Z',
    created_at: '2026-02-01T10:00:00Z',
  },
];

/** Mutable in-memory store – mutated during the demo session */
export const store: Record<string, any[]> = {
  profiles: [DEMO_PROFILE],
  cv_profiles: [DEMO_CV],
  job_listings: DEMO_JOBS,
  match_scores: DEMO_MATCHES,
  applications: DEMO_APPLICATIONS,
  alerts: DEMO_ALERTS,
};
